from enum import StrEnum


class ActorType(StrEnum):
    APPLICANT = "APPLICANT"
    INSTITUTION_WORKER = "INSTITUTION_WORKER"
    OFFICER = "OFFICER"
    ADMINISTRATOR = "ADMINISTRATOR"
    SYSTEM = "SYSTEM"


class ServiceType(StrEnum):
    STUDENT_PASS = "STUDENT_PASS"


class CaseStatus(StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    IN_PROCESS = "IN_PROCESS"
    ACTION_REQUIRED = "ACTION_REQUIRED"
    COMPLETED = "COMPLETED"
    WITHDRAWN = "WITHDRAWN"


class CaseStage(StrEnum):
    PRE_SUBMISSION = "PRE_SUBMISSION"
    IMMIGRATION_PROCESSING = "IMMIGRATION_PROCESSING"
    POST_ARRIVAL = "POST_ARRIVAL"
    CLOSED = "CLOSED"


class ApplicationType(StrEnum):
    NEW = "NEW"


class InstitutionType(StrEnum):
    UA = "UA"
    IPTS = "IPTS"


class ApplicantLocation(StrEnum):
    OUTSIDE_MALAYSIA = "OUTSIDE_MALAYSIA"


class SubmissionType(StrEnum):
    INITIAL = "INITIAL"
    SUPPLEMENTARY = "SUPPLEMENTARY"


class SubmissionChannel(StrEnum):
    EMGS = "EMGS"
    IMMIGRATION_COUNTER = "IMMIGRATION_COUNTER"
    ONLINE_PORTAL = "ONLINE_PORTAL"
    INSTITUTION_REPRESENTATIVE = "INSTITUTION_REPRESENTATIVE"


class DocumentType(StrEnum):
    PHOTO = "PHOTO"
    PASSPORT_BIODATA = "PASSPORT_BIODATA"
    PASSPORT_VISA_PAGES = "PASSPORT_VISA_PAGES"
    PASSPORT_OBSERVATION_PAGES = "PASSPORT_OBSERVATION_PAGES"
    PASSPORT_ALL_PAGES = "PASSPORT_ALL_PAGES"
    OFFER_LETTER = "OFFER_LETTER"
    HEALTH_DECLARATION = "HEALTH_DECLARATION"
    ACADEMIC_RECORDS = "ACADEMIC_RECORDS"
    ENGLISH_EVIDENCE = "ENGLISH_EVIDENCE"
    LOE = "LOE"
    NOC = "NOC"
    PERSONAL_BOND = "PERSONAL_BOND"
    YELLOW_FEVER_CERTIFICATE = "YELLOW_FEVER_CERTIFICATE"
    IMMIGRATION_RECEIPT = "IMMIGRATION_RECEIPT"
    OTHER = "OTHER"


class DocumentStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    VOID = "VOID"


class DocumentCheckResult(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    MANUAL_REVIEW = "MANUAL_REVIEW"
